name: Run all tests
on: workflow_call

jobs:
  node-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
      - uses: bahmutov/npm-install@v1
      - run: npm run format:check
      - run: npm run lint
      - run: npm test

  engine-specs:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby_version }} (${{ matrix.appraisal }})
    strategy:
      fail-fast: false
      matrix:
        # Test against active Ruby versions (https://endoflife.date/ruby)
        ruby_version: ["3.2", "3.3", "3.4"]
        # List appraisals to run in matrix for improved reporting
        appraisal: ["rails_7_2", "rails_8_0", "rails_8_1"]
        include:
          # Explicitly test against previously supported view component version
          # using the oldest supported Rails version. This can be removed when
          # we no longer want to test against view component 3.x directly
          - ruby_version: "3.2"
            appraisal: "view_component_3"
    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.appraisal }}.gemfile
    defaults:
      run:
        working-directory: engine
    steps:
      - uses: actions/checkout@v6
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby_version }}
          working-directory: engine
      - run: |
          bundle exec appraisal ${{ matrix.appraisal }} rake spec

  engine-lint:
    needs: engine-specs
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: engine
    steps:
      - uses: actions/checkout@v6
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: "3.4.5"
          working-directory: engine
      - run: bundle exec rubocop --format progress --format github
      - run: bundle exec erb_lint --lint-all

  demo-app:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: true
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc

      # Setup demo app
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4.5"
          bundler-cache: true
          working-directory: demo

      # Cache cypress binary
      - uses: actions/cache@v4
        with:
          path: /home/runner/.cache/Cypress
          key: cypress-binary-${{ hashFiles('package-lock.json') }}

      # Npm install
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: demo

      # Run rubocop against demo app code
      - run: bundle exec rubocop --format progress --format github
        working-directory: demo

      # Run asset build
      - run: ./bin/rails assets:precompile
        working-directory: demo

      # Run cypress tests
      - run: ./bin/rails cypress:run
        working-directory: demo
        env:
          CYPRESS_RAILS_CYPRESS_OPTS: "--browser chrome"

      # Archive test screenshots
      - uses: actions/upload-artifact@v5
        with:
          name: cypress-screenshots
          path: demo/cypress/screenshots
        if: ${{ failure() }}

  demo-app-backstop:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      CYPRESS_INSTALL_BINARY: 0
      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: true
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc

      # Setup demo app
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4.5"
          bundler-cache: true
          working-directory: demo

      - uses: bahmutov/npm-install@v1
        with:
          working-directory: demo

      - run: npm run backstop:ci
        working-directory: demo

      - uses: actions/upload-artifact@v5
        if: failure()
        with:
          name: backstop-report
          path: |
            demo/visual-regression/backstop_data/html_report
            demo/visual-regression/backstop_data/bitmaps_reference
            demo/visual-regression/backstop_data/bitmaps_test
          retention-days: 3
